### ISSUE TITLE
Estilizar `blockquote` convertido do Markdown

### ISSUE THREAD

**Issue by andrebnf** [andrebnf/nt-listas-excc#10]
O conteúdo gerado no site a partir do markdown está mostrando quotes (`>` no markdown) sem estilo:

Estilo atual: 
![image](https://user-images.githubusercontent.com/1435403/181647913-be629a93-7df3-43f8-9fe8-5d8a04dffc19.png)

Estilo desejado:
![image](https://user-images.githubusercontent.com/1435403/181647965-da649b0c-70f2-47ae-9e8a-6f4cd59ed294.png)

CSS para atingir o desejado:

```css
blockquote {
  margin-left: 0;
  padding-left: 24px;
  border-left: 3px solid #ccc;
}
```
